version: '3'
services:
  app:
    image: inktank
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME
      # - MONGODB_PASSWORD
      # - MONGODB_DATABASE
      - MONGODB_CONNECTION_STRING=mongodb://mongo/inktank
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
  mongo:
    image: mongo
    ports:
      - 27017:27017
